sudo: false
language: rust

cache:
  cargo: true
  directories:
    - tests/rust

rust:
  - nightly
  - stable
  - beta
  - 1.15.1

before_script:
  - set -o errexit

script:
  - cargo build --no-default-features
  - cargo build
  - cargo build --features full
  - cargo build --features 'fold visit visit-mut'
  - cargo build --features 'full fold visit visit-mut'
  - cargo build --no-default-features --features derive
  - cargo build --no-default-features --features 'derive parsing'
  - cargo build --no-default-features --features 'derive printing'
  - cargo build --no-default-features --features full
  - cargo build --no-default-features --features 'full parsing'
  - cargo build --no-default-features --features 'full printing'
  - cargo build --no-default-features --features 'full parsing printing'
  - cargo build --no-default-features --features 'fold visit visit-mut parsing printing'
  - cargo build --no-default-features --features 'full fold visit visit-mut parsing printing'

matrix:
  include:
    - rust: nightly
      env: ROLE=test
      script:
        - cargo test --all-features --release
    - rust: nightly
      env: ROLE=codegen
      script:
        - (cd codegen && cargo run)
        - git diff --exit-code
    - rust: nightly
      env: ROLE=minimal
      script:
        - cargo update -Z minimal-versions
        - cargo build --all-features
    - rust: nightly
      env: ROLE=clippy
      script:
        - cargo install clippy --debug --force || exit
        - cargo clippy --all-features -- -Dclippy
  allow_failures:
    - rust: nightly
      env: ROLE=clippy
      script:
        - cargo install clippy --debug --force || exit
        - cargo clippy --all-features -- -Dclippy
  fast_finish: true

env:
  matrix:
    - ROLE=build
  global:
    - RUST_MIN_STACK=20000000
