sudo: false
language: rust

rust:
  - nightly
  - stable
  - beta
  - 1.15.1

before_script:
  - set -o errexit

script:
  - shopt -s expand_aliases
  - alias build="cargo build ${TARGET+--target=$TARGET}"
  - build --no-default-features
  - build
  - build --features full
  - build --features 'fold visit visit-mut'
  - build --features 'full fold visit visit-mut'
  - build --no-default-features --features derive
  - build --no-default-features --features 'derive parsing'
  - build --no-default-features --features 'derive printing'
  - build --no-default-features --features full
  - build --no-default-features --features 'full parsing'
  - build --no-default-features --features 'full printing'
  - build --no-default-features --features 'full parsing printing'
  - build --no-default-features --features 'fold visit visit-mut parsing printing'
  - build --no-default-features --features 'full fold visit visit-mut parsing printing'

matrix:
  include:
    - rust: nightly
      env: ROLE=test
      script:
        - cargo test --all-features --release
    - rust: nightly
      env: ROLE=codegen
      script:
        - (cd codegen && cargo run)
        - git diff --exit-code
    - rust: nightly
      env: ROLE=minimal
      script:
        - cargo update -Z minimal-versions
        - cargo build --all-features
    - rust: nightly
      env: ROLE=clippy
      script:
        - rustup component add clippy-preview
        - cargo clippy --all-features
    - rust: nightly
      env: TARGET=wasm32-unknown-unknown
      install:
        - rustup target add "${TARGET}"
  allow_failures:
    - rust: nightly
      env: ROLE=clippy
  fast_finish: true
