[package]
name = "heapsize_derive"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { path = "../../.." }
quote = "0.6"
proc-macro2 = { version = "0.4", features = ["nightly"] }
