[package]
name = "trace-var"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { path = "../../../", features = ["full", "fold"] }
quote = "0.6"
proc-macro2 = { version = "0.4", features = ["nightly"] }
