[package]
name = "syn_codegen"
version = "0.1.0"
authors = ["Nika Layzell <nika@thelayzells.com>"]

publish = false # this is an internal crate which should never be published

[dependencies]
syn = { path = "..", features = ["full", "extra-traits"] }
quote = "0.6"
failure = "0.1"
inflections = "1.1"
proc-macro2 = "0.4"

[patch.crates-io]
quote = { git = 'https://github.com/dtolnay/quote' }
