[package]
name = "dump-syntax"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies.syn]
path = "../.."
default-features = false
features = ["parsing", "full", "extra-traits"]

[[bin]]
name = "dump-syntax"
path = "main.rs"
